<?php

namespace Database\Seeders;

use App\Models\Hebergement;
use App\Models\User;
use Illuminate\Database\Seeder;

class BookingComHebergementSeeder extends Seeder
{
    public function run(): void
    {
        $host = User::where('role', 'host')->where('email', 'maurice@hebergements.bj')->first();
        if (!$host) return;

        $hebergements = [

            // ═══════════════════════════════════════════════
            //  COTONOU
            // ═══════════════════════════════════════════════

            [
                'titre'             => 'Sofitel Cotonou Marina Hotel & Spa',
                'description'       => 'Palace 5 étoiles en bord de mer à Cotonou. Piscine à débordement face à l\'Atlantique, spa de luxe, 3 restaurants gastronomiques et 200 chambres vues océan. L\'adresse la plus prestigieuse du Bénin.',
                'type'              => 'hotel',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 200,
                'nombre_lits'       => 200,
                'nombre_salles_bain'=> 200,
                'capacite_max'      => 400,
                'prix_par_nuit'     => 310000,
                'adresse'           => 'Boulevard de la Marina',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3562,
                'longitude'         => 2.4389,
                'statut'            => 'actif',
                'image_principale'  => 'https://www.ahstatic.com/photos/b845_ho_00_p_1024x768.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'spa', 'restaurant', 'bar', 'parking', 'gym', 'salle_conference', 'vue_mer', 'petit_dejeuner']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés', 'check-in 15h', 'check-out 12h']),
                'note_moyenne'      => 4.80,
                'nombre_avis'       => 847,
            ],
            [
                'titre'             => 'Golden Tulip Le Diplomate Cotonou',
                'description'       => 'Hôtel 5 étoiles emblématique de Cotonou avec vue panoramique sur la mer et la ville. Restaurant gastronomique, piscine extérieure, centre d\'affaires et service conciergerie 24h/24.',
                'type'              => 'hotel',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 120,
                'nombre_lits'       => 120,
                'nombre_salles_bain'=> 120,
                'capacite_max'      => 240,
                'prix_par_nuit'     => 200000,
                'adresse'           => 'Boulevard de la Marina, Haie Vive',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3589,
                'longitude'         => 2.4361,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/89/1a/8a/golden-suite.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'gym', 'spa', 'salle_conference', 'vue_mer']),
                'regles_maison'     => json_encode(['non-fumeur', 'check-in 14h', 'check-out 12h', 'animaux non autorisés']),
                'note_moyenne'      => 4.70,
                'nombre_avis'       => 1243,
            ],
            [
                'titre'             => 'Mercure Cotonou Nouveau Palais Hotel',
                'description'       => 'Hôtel 4 étoiles de la chaîne Accor au cœur du quartier des affaires de Cotonou. Piscine panoramique au 7ème étage, restaurant, bar et 120 chambres modernes. Idéal pour les voyageurs d\'affaires.',
                'type'              => 'hotel',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 120,
                'nombre_lits'       => 120,
                'nombre_salles_bain'=> 120,
                'capacite_max'      => 240,
                'prix_par_nuit'     => 185000,
                'adresse'           => 'Avenue Jean-Paul II',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3627,
                'longitude'         => 2.4283,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/1e/96/d2/mercure-cotonou.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'gym', 'salle_conference', 'vue_ville']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 4.40,
                'nombre_avis'       => 932,
            ],
            [
                'titre'             => 'Maison Rouge Cotonou',
                'description'       => 'Boutique-hôtel de charme en bord de mer à Haie Vive. Décoration raffinée mêlant art contemporain africain et confort moderne. Piscine, restaurant gastronomique et service personnalisé d\'exception.',
                'type'              => 'hotel',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 25,
                'nombre_lits'       => 25,
                'nombre_salles_bain'=> 25,
                'capacite_max'      => 50,
                'prix_par_nuit'     => 180000,
                'adresse'           => 'Haie Vive, Rue des Pêcheurs',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3593,
                'longitude'         => 2.4371,
                'statut'            => 'actif',
                'image_principale'  => 'https://hotel-benin-maison-rouge-cotonou.com/wp-content/uploads/2023/06/hotel-maison-rouge-cotonou-benin-00003.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'spa', 'petit_dejeuner', 'vue_mer']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés', 'calme après 22h']),
                'note_moyenne'      => 4.90,
                'nombre_avis'       => 689,
            ],
            [
                'titre'             => 'Benin Royal Hotel',
                'description'       => 'Grand hôtel 4 étoiles au centre de Cotonou avec piscine, 3 restaurants, bar panoramique et centre de conférences. 90 chambres luxueuses avec vue ville. Le choix des diplomates et hommes d\'affaires.',
                'type'              => 'hotel',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 90,
                'nombre_lits'       => 90,
                'nombre_salles_bain'=> 90,
                'capacite_max'      => 180,
                'prix_par_nuit'     => 120000,
                'adresse'           => 'Avenue Clozel, Quartier Ganhi',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3664,
                'longitude'         => 2.4162,
                'statut'            => 'actif',
                'image_principale'  => 'https://s3-cdn.hotellinksolutions.com/hls/data/2540/website/general/bn/normal_normal_banner1-benin-royal-hotel-compressor.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'gym', 'salle_conference', 'petit_dejeuner']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 4.20,
                'nombre_avis'       => 1156,
            ],
            [
                'titre'             => 'Azalaï Hôtel de la Plage Cotonou',
                'description'       => 'Hôtel 4 étoiles de la chaîne panafricaine Azalaï, directement sur la plage de Cotonou. Piscine face à l\'océan, restaurant de fruits de mer, terrasse panoramique et accès privé à la plage.',
                'type'              => 'hotel',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 80,
                'nombre_lits'       => 80,
                'nombre_salles_bain'=> 80,
                'capacite_max'      => 160,
                'prix_par_nuit'     => 95000,
                'adresse'           => 'Boulevard de la République, Plage',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3701,
                'longitude'         => 2.4195,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/74/49/7c/azalai-hotel-cotonou.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'plage', 'vue_ocean']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 4.10,
                'nombre_avis'       => 534,
            ],
            [
                'titre'             => 'Best Western Premier Benin Hotel',
                'description'       => 'Hôtel 4 étoiles Best Western dans le quartier résidentiel de Cotonou. Piscine, restaurant international, salle de sport et 72 chambres contemporaines. Service de navette aéroport inclus.',
                'type'              => 'hotel',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 72,
                'nombre_lits'       => 72,
                'nombre_salles_bain'=> 72,
                'capacite_max'      => 144,
                'prix_par_nuit'     => 110000,
                'adresse'           => 'Quartier Haie Vive',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3598,
                'longitude'         => 2.4345,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/04/7e/fe/best-western-plus-nobila.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'gym', 'navette_aeroport']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 4.30,
                'nombre_avis'       => 418,
            ],
            [
                'titre'             => 'Hôtel Bénin Marina',
                'description'       => 'Hôtel 4 étoiles au bord de la marina de Cotonou. Vue exceptionnelle sur l\'Atlantique, restaurant gastronomique, piscine à débordement et 95 chambres spacieuses. Accès direct aux plages.',
                'type'              => 'hotel',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 95,
                'nombre_lits'       => 95,
                'nombre_salles_bain'=> 95,
                'capacite_max'      => 190,
                'prix_par_nuit'     => 130000,
                'adresse'           => 'Boulevard de la Marina Est',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3571,
                'longitude'         => 2.4401,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/19/5f/ba/benin-marina-hotel.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'vue_mer', 'spa']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés', 'check-in 14h']),
                'note_moyenne'      => 4.50,
                'nombre_avis'       => 362,
            ],
            [
                'titre'             => 'Ibis Cotonou',
                'description'       => 'Hôtel 3 étoiles de la chaîne Ibis/Accor, idéalement situé au centre de Cotonou. Rapport qualité-prix excellent, restaurant, bar et 100 chambres confortables. Parking sécurisé inclus.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 100,
                'nombre_lits'       => 100,
                'nombre_salles_bain'=> 100,
                'capacite_max'      => 200,
                'prix_par_nuit'     => 52000,
                'adresse'           => 'Rue du Gouverneur Général Angoulvant',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3682,
                'longitude'         => 2.4191,
                'statut'            => 'actif',
                'image_principale'  => 'https://www.ahstatic.com/photos/6681_ho_00_p_1024x768.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'bar', 'parking', 'petit_dejeuner']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 3.80,
                'nombre_avis'       => 1478,
            ],
            [
                'titre'             => 'Hôtel Les Orchidées Cotonou',
                'description'       => 'Hôtel 3 étoiles élégant au cœur de Cotonou. Décoration florale, piscine, restaurant avec terrasse et 45 chambres climatisées. Petit-déjeuner buffet inclus. À proximité des principales ambassades.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 45,
                'nombre_lits'       => 45,
                'nombre_salles_bain'=> 45,
                'capacite_max'      => 90,
                'prix_par_nuit'     => 78000,
                'adresse'           => 'Rue du Lycée Toffa',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3715,
                'longitude'         => 2.4211,
                'statut'            => 'actif',
                'image_principale'  => 'https://www.hotellesorchidees.com/img/slider/1.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'parking', 'petit_dejeuner']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 4.60,
                'nombre_avis'       => 287,
            ],
            [
                'titre'             => 'Hôtel Continental Cotonou',
                'description'       => 'Hôtel 3 étoiles en plein centre de Cotonou, à deux pas du grand marché Dantokpa. Chambres climatisées, restaurant de cuisine internationale et africaine, bar lounge et parking sécurisé.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 60,
                'nombre_lits'       => 60,
                'nombre_salles_bain'=> 60,
                'capacite_max'      => 120,
                'prix_par_nuit'     => 65000,
                'adresse'           => 'Avenue Steinmetz, Centre-Ville',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3648,
                'longitude'         => 2.4178,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/41/35/8b/hotel-continental-cotonou.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'bar', 'parking']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 3.90,
                'nombre_avis'       => 342,
            ],
            [
                'titre'             => 'Le Kare Ebene',
                'description'       => 'Boutique-hôtel design au quartier Jéricho. Décoration africaine contemporaine, rooftop bar avec vue sur la ville, restaurant fusion et 30 chambres au style unique. L\'hôtel préféré des créatifs.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 30,
                'nombre_lits'       => 30,
                'nombre_salles_bain'=> 30,
                'capacite_max'      => 60,
                'prix_par_nuit'     => 85000,
                'adresse'           => 'Quartier Jéricho',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3782,
                'longitude'         => 2.4088,
                'statut'            => 'actif',
                'image_principale'  => 'https://www.lekareebene.com/wp-content/uploads/2025/05/bienvenu-au-kare-ebene-boutik-hotel-1536x1025.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'bar', 'parking', 'rooftop', 'petit_dejeuner']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 4.50,
                'nombre_avis'       => 198,
            ],
            [
                'titre'             => 'Villa Karo Cotonou',
                'description'       => 'Villa-hôtel intimiste dans un jardin tropical à Cotonou. 12 suites décorées par des artistes béninois, piscine privée, restaurant gastronomique et galerie d\'art. Une expérience culturelle unique.',
                'type'              => 'villa',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 12,
                'nombre_lits'       => 12,
                'nombre_salles_bain'=> 12,
                'capacite_max'      => 24,
                'prix_par_nuit'     => 150000,
                'adresse'           => 'Quartier Agla, Rue des Artistes',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3511,
                'longitude'         => 2.4098,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/b7/2a/1d/villa-karo.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'jardin', 'parking', 'galerie_art']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés', 'check-in sur RDV']),
                'note_moyenne'      => 4.80,
                'nombre_avis'       => 156,
            ],
            [
                'titre'             => 'Tropical Hôtel Cotonou',
                'description'       => 'Hôtel 3 étoiles avec cadre tropical, piscine entourée de cocotiers et restaurant en plein air. Situé dans le quartier Fidjrossè, à 5 minutes de la plage. Ambiance détendue et service convivial.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 55,
                'nombre_lits'       => 55,
                'nombre_salles_bain'=> 55,
                'capacite_max'      => 110,
                'prix_par_nuit'     => 68000,
                'adresse'           => 'Quartier Fidjrossè, Route des Pêcheurs',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3445,
                'longitude'         => 2.3971,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/d1/6d/4b/tropical-hotel.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'jardin']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 4.10,
                'nombre_avis'       => 274,
            ],
            [
                'titre'             => 'Hôtel du Lac Cotonou',
                'description'       => 'Hôtel 3 étoiles avec vue sur le lac Nokoué. Terrasse panoramique, restaurant de spécialités lacustres et 40 chambres confortables. À proximité du marché flottant et des pirogues vers Ganvié.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 40,
                'nombre_lits'       => 40,
                'nombre_salles_bain'=> 40,
                'capacite_max'      => 80,
                'prix_par_nuit'     => 58000,
                'adresse'           => 'Route du Lac Nokoué',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.4012,
                'longitude'         => 2.3901,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/b9/39/22/pool-side.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'bar', 'parking', 'vue_lac', 'terrasse']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 4.20,
                'nombre_avis'       => 188,
            ],
            [
                'titre'             => 'Hôtel Croix du Sud Cotonou',
                'description'       => 'Hôtel familial 3 étoiles dans le quartier calme de Zogbo. Piscine, restaurant avec terrasse ombragée et 38 chambres spacieuses. Idéal pour les familles et séjours prolongés.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 38,
                'nombre_lits'       => 38,
                'nombre_salles_bain'=> 38,
                'capacite_max'      => 76,
                'prix_par_nuit'     => 60000,
                'adresse'           => 'Quartier Zogbo, Route de l\'Aéroport',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3512,
                'longitude'         => 2.3845,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/4a/6b/70/hotel-croix-du-sud.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'parking', 'jardin']),
                'regles_maison'     => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne'      => 4.00,
                'nombre_avis'       => 215,
            ],
            [
                'titre'             => 'Benin Berge Hotel',
                'description'       => 'Hôtel moderne et bien situé dans le quartier diplomatique. Chambres spacieuses avec balcon, restaurant panoramique et salon lounge. Proche des ambassades et des centres d\'affaires.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 35,
                'nombre_lits'       => 35,
                'nombre_salles_bain'=> 35,
                'capacite_max'      => 70,
                'prix_par_nuit'     => 72000,
                'adresse'           => 'Quartier Haie Vive, Avenue Steinmetz',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3601,
                'longitude'         => 2.4322,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/82/f5/50/benin-berge-hotel.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'bar', 'balcon']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 4.90,
                'nombre_avis'       => 94,
            ],
            [
                'titre'             => 'La Maison de Canelya',
                'description'       => 'Maison d\'hôtes de charme au quartier Agla. Jardin fleuri avec piscine privée, 6 chambres décorées avec des textiles locaux et restaurant de cuisine créole béninoise. Ambiance familiale.',
                'type'              => 'maison',
                'categorie'         => 'confort',
                'nombre_pieces'     => 6,
                'nombre_lits'       => 8,
                'nombre_salles_bain'=> 3,
                'capacite_max'      => 12,
                'prix_par_nuit'     => 65000,
                'adresse'           => 'Quartier Agla',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3512,
                'longitude'         => 2.4101,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/4d/f8/c0/la-maison-de-canelia.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'jardin', 'parking', 'cuisine', 'petit_dejeuner']),
                'regles_maison'     => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne'      => 4.60,
                'nombre_avis'       => 312,
            ],
            [
                'titre'             => 'Résidence Hôtel Perle Bleue',
                'description'       => 'Résidence hôtelière 3 étoiles à Fidjrossè proposant des appartements entièrement équipés. Idéale pour les séjours longue durée. Piscine commune, sécurité 24h/24 et accès à la plage à 10 minutes.',
                'type'              => 'appartement',
                'categorie'         => 'confort',
                'nombre_pieces'     => 3,
                'nombre_lits'       => 2,
                'nombre_salles_bain'=> 1,
                'capacite_max'      => 4,
                'prix_par_nuit'     => 62000,
                'adresse'           => 'Quartier Fidjrossè',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3441,
                'longitude'         => 2.3964,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1f/3c/d8/a9/residence-perle-bleue.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'cuisine', 'piscine', 'parking', 'terrasse']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 5.00,
                'nombre_avis'       => 47,
            ],
            [
                'titre'             => 'Residence MaryHouse',
                'description'       => 'Résidence chaleureuse au quartier Cadjehoun, à 5 minutes de l\'aéroport. Petit-déjeuner maison inclus, chambres propres et climatisées. La solution économique idéale pour les voyageurs en transit.',
                'type'              => 'appartement',
                'categorie'         => 'budget',
                'nombre_pieces'     => 2,
                'nombre_lits'       => 2,
                'nombre_salles_bain'=> 1,
                'capacite_max'      => 4,
                'prix_par_nuit'     => 36000,
                'adresse'           => 'Quartier Cadjehoun',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3579,
                'longitude'         => 2.3812,
                'statut'            => 'actif',
                'image_principale'  => 'https://maryhouse.bj/wp-content/uploads/2024/07/img-bannerV09-1920x1315.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'petit_dejeuner', 'cuisine']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 4.70,
                'nombre_avis'       => 428,
            ],
            [
                'titre'             => 'Résidence Ivoire Cotonou',
                'description'       => 'Résidence haut de gamme dans le quartier résidentiel des Cocotiers. Appartements meublés avec goût, sécurité 24h/24 et service conciergerie. Idéale pour les expatriés et les familles.',
                'type'              => 'appartement',
                'categorie'         => 'confort',
                'nombre_pieces'     => 4,
                'nombre_lits'       => 3,
                'nombre_salles_bain'=> 2,
                'capacite_max'      => 6,
                'prix_par_nuit'     => 68000,
                'adresse'           => 'Quartier Cocotiers',
                'ville'             => 'Cotonou',
                'code_postal'       => '01',
                'latitude'          => 6.3521,
                'longitude'         => 2.4278,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/a2/58/3a/caption.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'cuisine', 'parking', 'terrasse', 'sécurité_24h']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 4.80,
                'nombre_avis'       => 73,
            ],
            [
                'titre'             => 'Auberge Kalaupapa',
                'description'       => 'Auberge de charme à Abomey-Calavi, à 10 minutes de Cotonou et à proximité des pirogues vers Ganvié, le village lacustre. Ambiance conviviale, cuisine locale et jardin verdoyant.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 15,
                'nombre_lits'       => 18,
                'nombre_salles_bain'=> 15,
                'capacite_max'      => 30,
                'prix_par_nuit'     => 55000,
                'adresse'           => 'Quartier Godomey, Abomey-Calavi',
                'ville'             => 'Abomey-Calavi',
                'code_postal'       => '01',
                'latitude'          => 6.4487,
                'longitude'         => 2.3559,
                'statut'            => 'actif',
                'image_principale'  => 'https://auberge-kalaupapa.org/wp-content/uploads/2025/11/kal-chbleue-2024-2-bdef.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'jardin']),
                'regles_maison'     => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne'      => 4.90,
                'nombre_avis'       => 167,
            ],

            // ═══════════════════════════════════════════════
            //  OUIDAH
            // ═══════════════════════════════════════════════

            [
                'titre'             => 'Casa del Papa Resort & SPA',
                'description'       => 'Resort 4 étoiles avec vue sur le lagon de Ouidah. Spa, piscine lagon, restaurant de poissons frais et bungalows sur pilotis. Entre lagon et océan, à deux pas de la Route de l\'Esclave.',
                'type'              => 'resort',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 40,
                'nombre_lits'       => 40,
                'nombre_salles_bain'=> 40,
                'capacite_max'      => 80,
                'prix_par_nuit'     => 88000,
                'adresse'           => 'Route de la Bouche du Roy',
                'ville'             => 'Ouidah',
                'code_postal'       => '03',
                'latitude'          => 6.3583,
                'longitude'         => 2.0841,
                'statut'            => 'actif',
                'image_principale'  => 'https://wa-uploads.profitroom.com/casadelpapa/1920x1080/17053093858117_paisaje2.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'spa', 'parking', 'petit_dejeuner', 'vue_lagon']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 4.00,
                'nombre_avis'       => 761,
            ],
            [
                'titre'             => 'Domaine de la Palmeraie',
                'description'       => 'Domaine de luxe niché au cœur d\'une palmeraie centenaire à Ouidah. Villas privées avec piscine, chef personnel, hammam et activités culturelles (vaudou, musées). Une expérience unique.',
                'type'              => 'villa',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 6,
                'nombre_lits'       => 8,
                'nombre_salles_bain'=> 4,
                'capacite_max'      => 12,
                'prix_par_nuit'     => 200000,
                'adresse'           => 'Route de Ouidah-Lomé',
                'ville'             => 'Ouidah',
                'code_postal'       => '03',
                'latitude'          => 6.3611,
                'longitude'         => 2.0888,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/ac/62/91/domaine-de-la-palmeraie.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'cuisine', 'jardin', 'parking', 'chef_personnel', 'spa']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés', 'check-in sur RDV']),
                'note_moyenne'      => 5.00,
                'nombre_avis'       => 89,
            ],
            [
                'titre'             => 'Le Jardin Secret Ouidah',
                'description'       => 'Éco-lodge de charme dans un jardin tropical à Ouidah, classée ville du patrimoine mondial. Bungalows en matériaux naturels, piscine biologique et restaurant 100% local. Idéal pour l\'immersion culturelle.',
                'type'              => 'resort',
                'categorie'         => 'confort',
                'nombre_pieces'     => 14,
                'nombre_lits'       => 14,
                'nombre_salles_bain'=> 14,
                'capacite_max'      => 28,
                'prix_par_nuit'     => 58000,
                'adresse'           => 'Rue des Colons, Ouidah',
                'ville'             => 'Ouidah',
                'code_postal'       => '03',
                'latitude'          => 6.3622,
                'longitude'         => 2.0862,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/70/e4/2c/le-jardin-secret.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'jardin', 'parking', 'petit_dejeuner']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux acceptés sur demande']),
                'note_moyenne'      => 4.70,
                'nombre_avis'       => 234,
            ],
            [
                'titre'             => 'Djegba Hotel Ouidah',
                'description'       => 'Hôtel 2 étoiles fonctionnel avec vue sur l\'océan à Ouidah. Idéal pour explorer la ville historique, la Forêt des Pythons et la Route de l\'Esclave. Restaurant de cuisine locale.',
                'type'              => 'hotel',
                'categorie'         => 'budget',
                'nombre_pieces'     => 15,
                'nombre_lits'       => 15,
                'nombre_salles_bain'=> 15,
                'capacite_max'      => 30,
                'prix_par_nuit'     => 35000,
                'adresse'           => 'Rue de l\'Atlantique, Ouidah',
                'ville'             => 'Ouidah',
                'code_postal'       => '03',
                'latitude'          => 6.6214,
                'longitude'         => 2.0855,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/91/e5/15/trouvez-l-equilibre-parfait.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'vue_ocean']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 3.70,
                'nombre_avis'       => 178,
            ],

            // ═══════════════════════════════════════════════
            //  GRAND POPO
            // ═══════════════════════════════════════════════

            [
                'titre'             => 'Asva Beach Resort',
                'description'       => 'Resort balnéaire de luxe directement sur l\'Atlantique à Grand Popo. Villas avec terrasse privée, piscine à débordement, restaurant de fruits de mer et accès direct à la plage. Le paradis de la côte béninoise.',
                'type'              => 'resort',
                'categorie'         => 'luxe',
                'nombre_pieces'     => 20,
                'nombre_lits'       => 20,
                'nombre_salles_bain'=> 20,
                'capacite_max'      => 40,
                'prix_par_nuit'     => 155000,
                'adresse'           => 'Bord de l\'Atlantique, Grand Popo',
                'ville'             => 'Grand Popo',
                'code_postal'       => '06',
                'latitude'          => 6.2789,
                'longitude'         => 1.8244,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/8b/15/f3/asva-beach-resort.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'spa', 'plage', 'parking']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés', 'check-in 15h']),
                'note_moyenne'      => 4.80,
                'nombre_avis'       => 143,
            ],
            [
                'titre'             => 'Hotel Awalé Plage',
                'description'       => 'Hôtel de plage à Grand Popo, accessible et convivial. Bungalows sous les cocotiers, accès direct à l\'océan et restaurant avec fraîche pêche du jour. L\'adresse idéale pour des vacances authentiques en famille.',
                'type'              => 'hotel',
                'categorie'         => 'budget',
                'nombre_pieces'     => 20,
                'nombre_lits'       => 20,
                'nombre_salles_bain'=> 20,
                'capacite_max'      => 40,
                'prix_par_nuit'     => 32000,
                'adresse'           => 'Bord de Mer, Grand Popo',
                'ville'             => 'Grand Popo',
                'code_postal'       => '06',
                'latitude'          => 6.2817,
                'longitude'         => 1.8269,
                'statut'            => 'actif',
                'image_principale'  => 'https://www.hotel-benin-awaleplage.com/wp-content/uploads/2023/06/header-site-awale-plage-2023.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'plage', 'parking']),
                'regles_maison'     => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne'      => 3.60,
                'nombre_avis'       => 523,
            ],
            [
                'titre'             => 'Auberge de Grand-Popo',
                'description'       => 'Auberge emblématique de la côte béninoise, ouverte depuis 1988. Bungalows pittoresques sur la plage, restaurant de cuisine franco-béninoise et ambiance bohème. Un classique que tout voyageur doit connaître.',
                'type'              => 'hotel',
                'categorie'         => 'budget',
                'nombre_pieces'     => 18,
                'nombre_lits'       => 18,
                'nombre_salles_bain'=> 18,
                'capacite_max'      => 36,
                'prix_par_nuit'     => 40000,
                'adresse'           => 'Route Côtière, Grand Popo',
                'ville'             => 'Grand Popo',
                'code_postal'       => '06',
                'latitude'          => 6.2831,
                'longitude'         => 1.8295,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/b9/df/76/farafina-hotel.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'bar', 'plage', 'jardin']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 4.30,
                'nombre_avis'       => 389,
            ],

            // ═══════════════════════════════════════════════
            //  PORTO-NOVO
            // ═══════════════════════════════════════════════

            [
                'titre'             => 'Résidences Ouadada Porto-Novo',
                'description'       => 'Résidence hôtelière de standing dans la capitale du Bénin. Appartements meublés avec terrasse, accès au jardin et parking sécurisé. À 500m du Palais Royal et des musées ethnographiques.',
                'type'              => 'appartement',
                'categorie'         => 'confort',
                'nombre_pieces'     => 3,
                'nombre_lits'       => 2,
                'nombre_salles_bain'=> 1,
                'capacite_max'      => 4,
                'prix_par_nuit'     => 56000,
                'adresse'           => 'Quartier Ouando, Porto-Novo',
                'ville'             => 'Porto-Novo',
                'code_postal'       => '02',
                'latitude'          => 6.4913,
                'longitude'         => 2.6244,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1e/85/c2/7a/residences-ouadada.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'cuisine', 'parking', 'jardin', 'terrasse']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 4.80,
                'nombre_avis'       => 152,
            ],
            [
                'titre'             => 'Hôtel Beaurivage Porto-Novo',
                'description'       => 'Hôtel 3 étoiles au bord de la lagune de Porto-Novo. Terrasse avec vue sur l\'eau, restaurant de spécialités locales et 35 chambres climatisées. Idéal pour découvrir la capitale et ses musées.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 35,
                'nombre_lits'       => 35,
                'nombre_salles_bain'=> 35,
                'capacite_max'      => 70,
                'prix_par_nuit'     => 52000,
                'adresse'           => 'Boulevard de la Lagune, Porto-Novo',
                'ville'             => 'Porto-Novo',
                'code_postal'       => '02',
                'latitude'          => 6.4947,
                'longitude'         => 2.6289,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/67/03/19/hotel-beaurivage.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'vue_lagune', 'terrasse']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 4.10,
                'nombre_avis'       => 203,
            ],
            [
                'titre'             => 'Hôtel Silva Porto-Novo',
                'description'       => 'Hôtel économique et propre au centre de Porto-Novo. Chambres climatisées, restaurant de cuisine africaine et accès Wi-Fi. La solution budget pour explorer la capitale historique du Bénin.',
                'type'              => 'hotel',
                'categorie'         => 'budget',
                'nombre_pieces'     => 22,
                'nombre_lits'       => 22,
                'nombre_salles_bain'=> 22,
                'capacite_max'      => 44,
                'prix_par_nuit'     => 28000,
                'adresse'           => 'Quartier Centre, Porto-Novo',
                'ville'             => 'Porto-Novo',
                'code_postal'       => '02',
                'latitude'          => 6.4961,
                'longitude'         => 2.6301,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/2d/e3/f1/hotel-silva.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'parking']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 3.80,
                'nombre_avis'       => 134,
            ],

            // ═══════════════════════════════════════════════
            //  ABOMEY
            // ═══════════════════════════════════════════════

            [
                'titre'             => 'Chez Monique Abomey',
                'description'       => 'Auberge familiale à deux pas des Palais Royaux d\'Abomey (UNESCO). Cuisine béninoise traditionnelle, cour intérieure ombragée et accueil chaleureux. La base idéale pour découvrir la capitale du royaume du Dahomey.',
                'type'              => 'maison',
                'categorie'         => 'budget',
                'nombre_pieces'     => 3,
                'nombre_lits'       => 4,
                'nombre_salles_bain'=> 1,
                'capacite_max'      => 6,
                'prix_par_nuit'     => 22000,
                'adresse'           => 'Route Abomey-Bohicon',
                'ville'             => 'Abomey',
                'code_postal'       => '04',
                'latitude'          => 7.2012,
                'longitude'         => 1.9891,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/12/72/f5/l-univers-de-chez-monique.jpg',
                'amenagements'      => json_encode(['cuisine', 'jardin', 'wifi']),
                'regles_maison'     => json_encode(['non-fumeur', 'pas de bruit après 21h']),
                'note_moyenne'      => 3.30,
                'nombre_avis'       => 267,
            ],
            [
                'titre'             => 'Chez Sabine Abomey',
                'description'       => 'Auberge authentique avec guide touristique francophone pour les Palais d\'Abomey. Petit-déjeuner local inclus, cuisine traditionnelle sur demande et ambiance culturelle immersive.',
                'type'              => 'maison',
                'categorie'         => 'budget',
                'nombre_pieces'     => 4,
                'nombre_lits'       => 5,
                'nombre_salles_bain'=> 2,
                'capacite_max'      => 8,
                'prix_par_nuit'     => 26000,
                'adresse'           => 'Quartier Djègan-Kpèvi, Abomey',
                'ville'             => 'Abomey',
                'code_postal'       => '04',
                'latitude'          => 7.1965,
                'longitude'         => 1.9934,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/c3/a6/99/chez-sabine.jpg',
                'amenagements'      => json_encode(['wifi', 'cuisine', 'jardin', 'petit_dejeuner']),
                'regles_maison'     => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne'      => 4.70,
                'nombre_avis'       => 198,
            ],

            // ═══════════════════════════════════════════════
            //  NATITINGOU
            // ═══════════════════════════════════════════════

            [
                'titre'             => 'Le Bélier Natitingou',
                'description'       => 'Hôtel confort dans la capitale de l\'Atacora. Base idéale pour visiter le Parc Pendjari (lions, éléphants, hippopotames) et les châteaux Tata Somba. Restaurant et guide safari disponibles.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 25,
                'nombre_lits'       => 25,
                'nombre_salles_bain'=> 25,
                'capacite_max'      => 50,
                'prix_par_nuit'     => 62000,
                'adresse'           => 'Rue Principale, Natitingou Centre',
                'ville'             => 'Natitingou',
                'code_postal'       => '10',
                'latitude'          => 10.3102,
                'longitude'         => 1.3812,
                'statut'            => 'actif',
                'image_principale'  => 'https://static.wixstatic.com/media/95638f_6231e3b308104e8c8f2aa29700755994~mv2_d_4608_3456_s_4_2.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'jardin', 'guide_safari']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 4.80,
                'nombre_avis'       => 178,
            ],
            [
                'titre'             => 'Gîte Chez Noël Natitingou',
                'description'       => 'Gîte authentique et chaleureux à Natitingou, tenu par un guide certifié du Parc Pendjari. Cuisine locale délicieuse, organisation de safaris et de visites des villages Somba. Ambiance familiale.',
                'type'              => 'maison',
                'categorie'         => 'budget',
                'nombre_pieces'     => 5,
                'nombre_lits'       => 6,
                'nombre_salles_bain'=> 2,
                'capacite_max'      => 10,
                'prix_par_nuit'     => 26000,
                'adresse'           => 'Quartier Centre, Natitingou',
                'ville'             => 'Natitingou',
                'code_postal'       => '10',
                'latitude'          => 10.3044,
                'longitude'         => 1.3800,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/12/ed/5f/caption.jpg',
                'amenagements'      => json_encode(['wifi', 'cuisine', 'jardin', 'parking']),
                'regles_maison'     => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne'      => 5.00,
                'nombre_avis'       => 112,
            ],

            // ═══════════════════════════════════════════════
            //  PARAKOU
            // ═══════════════════════════════════════════════

            [
                'titre'             => 'Hôtel Iya-Oasis Parakou',
                'description'       => 'Hôtel 3 étoiles à Parakou, la capitale économique du Nord-Bénin. Piscine, restaurant franco-africain, salles de réunion et 30 chambres spacieuses. Idéal pour explorer le nord du pays.',
                'type'              => 'hotel',
                'categorie'         => 'confort',
                'nombre_pieces'     => 30,
                'nombre_lits'       => 30,
                'nombre_salles_bain'=> 30,
                'capacite_max'      => 60,
                'prix_par_nuit'     => 48000,
                'adresse'           => 'Avenue de France, Parakou',
                'ville'             => 'Parakou',
                'code_postal'       => '07',
                'latitude'          => 9.3569,
                'longitude'         => 2.6287,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/91/15/0c/caption.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'piscine', 'parking', 'petit_dejeuner', 'salle_conference']),
                'regles_maison'     => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne'      => 5.00,
                'nombre_avis'       => 87,
            ],
            [
                'titre'             => 'Hôtel du Grand Marché Parakou',
                'description'       => 'Hôtel central à Parakou, en face du grand marché. Chambres climatisées, restaurant de cuisine locale et terrasse animée. La meilleure adresse pour vivre au rythme de la ville commerçante du nord.',
                'type'              => 'hotel',
                'categorie'         => 'budget',
                'nombre_pieces'     => 28,
                'nombre_lits'       => 28,
                'nombre_salles_bain'=> 28,
                'capacite_max'      => 56,
                'prix_par_nuit'     => 32000,
                'adresse'           => 'Place du Grand Marché, Parakou',
                'ville'             => 'Parakou',
                'code_postal'       => '07',
                'latitude'          => 9.3589,
                'longitude'         => 2.6301,
                'statut'            => 'actif',
                'image_principale'  => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/a4/72/88/hotel-du-grand-marche.jpg',
                'amenagements'      => json_encode(['wifi', 'climatisation', 'restaurant', 'parking']),
                'regles_maison'     => json_encode(['non-fumeur']),
                'note_moyenne'      => 4.00,
                'nombre_avis'       => 121,
            ],
        ];

        foreach ($hebergements as $data) {
            $data['user_id']             = $host->id;
            $data['date_verification']   = now();
            $data['nombre_reservations'] = 0;
            Hebergement::create($data);
        }
    }
}
