<?php

namespace Database\Seeders;

use App\Models\Hebergement;
use App\Models\User;
use Illuminate\Database\Seeder;

class TripAdvisorHebergementSeeder extends Seeder
{
    public function run(): void
    {
        $host = User::where('role', 'host')->where('email', 'maurice@hebergements.bj')->first();

        if (!$host) {
            return;
        }

        $hebergements = [
            [
                'titre' => 'Golden Tulip Le Diplomate Cotonou',
                'description' => 'Hôtel 5 étoiles emblématique de Cotonou offrant une vue panoramique sur la mer et la ville. Chambres spacieuses, restaurant gastronomique, piscine extérieure et centre d\'affaires complet. Idéal pour les voyageurs d\'affaires et les touristes exigeants.',
                'type' => 'hotel',
                'categorie' => 'luxe',
                'nombre_pieces' => 120,
                'nombre_lits' => 120,
                'nombre_salles_bain' => 120,
                'capacite_max' => 240,
                'prix_par_nuit' => 200000,
                'adresse' => 'Boulevard de la Marina, Haie Vive',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3589,
                'longitude' => 2.4361,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'gym', 'spa', 'salle_conference', 'vue_mer']),
                'regles_maison' => json_encode(['non-fumeur', 'check-in à 14h', 'check-out à 12h', 'animaux non autorisés']),
                'note_moyenne' => 4.70,
                'nombre_avis' => 333,
            ],
            [
                'titre' => 'Novotel Cotonou Orisha Hotel',
                'description' => 'Hôtel international de la chaîne Accor au cœur de Cotonou. Accès direct à la plage, piscine, restaurant et bar. Parfait pour les familles et les séjours d\'affaires. Service de navette aéroport disponible.',
                'type' => 'hotel',
                'categorie' => 'luxe',
                'nombre_pieces' => 150,
                'nombre_lits' => 150,
                'nombre_salles_bain' => 150,
                'capacite_max' => 300,
                'prix_par_nuit' => 150000,
                'adresse' => 'Avenue Jean-Paul II, Zone des Ambassades',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3627,
                'longitude' => 2.4283,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'gym', 'plage', 'salle_conference']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés', 'check-in à 15h']),
                'note_moyenne' => 4.30,
                'nombre_avis' => 647,
            ],
            [
                'titre' => 'Casa del Papa Resort & SPA',
                'description' => 'Resort de charme avec vue sur le lagon de Ouidah. Petit-déjeuner inclus, spa, piscine et restaurant. Cadre naturel exceptionnel entre lagon et océan. Idéal pour une escapade romantique ou culturelle.',
                'type' => 'resort',
                'categorie' => 'confort',
                'nombre_pieces' => 40,
                'nombre_lits' => 40,
                'nombre_salles_bain' => 40,
                'capacite_max' => 80,
                'prix_par_nuit' => 80000,
                'adresse' => 'Route de la Bouche du Roy',
                'ville' => 'Ouidah',
                'code_postal' => '03',
                'latitude' => 6.3583,
                'longitude' => 2.0841,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'spa', 'parking', 'petit_dejeuner', 'vue_lagon']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 4.00,
                'nombre_avis' => 275,
            ],
            [
                'titre' => 'Ibis Cotonou',
                'description' => 'Hôtel de la chaîne Ibis (Accor) situé au cœur de Cotonou. Petit-déjeuner inclus, restaurant, bar et parking sécurisé. Rapport qualité-prix excellent pour les séjours professionnels.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 100,
                'nombre_lits' => 100,
                'nombre_salles_bain' => 100,
                'capacite_max' => 200,
                'prix_par_nuit' => 50000,
                'adresse' => 'Rue du Gouverneur Général Angoulvant',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3682,
                'longitude' => 2.4191,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'restaurant', 'bar', 'parking', 'petit_dejeuner']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 3.80,
                'nombre_avis' => 338,
            ],
            [
                'titre' => 'Azalaï Hôtel Cotonou',
                'description' => 'Hôtel de la chaîne africaine Azalaï avec vue sur l\'océan Atlantique. Chambres confortables, restaurant, piscine et accès à la plage. Situé dans le quartier des affaires de Cotonou.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 80,
                'nombre_lits' => 80,
                'nombre_salles_bain' => 80,
                'capacite_max' => 160,
                'prix_par_nuit' => 75000,
                'adresse' => 'Boulevard de la République',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3701,
                'longitude' => 2.4195,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'vue_ocean']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 3.50,
                'nombre_avis' => 128,
            ],
            [
                'titre' => 'Maison Rouge Cotonou',
                'description' => 'Boutique-hôtel de luxe au cœur de Cotonou. Décoration raffinée, service personnalisé, petit-déjeuner gastronomique inclus. Idéal pour les voyageurs qui recherchent une expérience unique et authentique.',
                'type' => 'hotel',
                'categorie' => 'luxe',
                'nombre_pieces' => 25,
                'nombre_lits' => 25,
                'nombre_salles_bain' => 25,
                'capacite_max' => 50,
                'prix_par_nuit' => 180000,
                'adresse' => 'Rue du Gouverneur, Haie Vive',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3593,
                'longitude' => 2.4371,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'restaurant', 'bar', 'parking', 'petit_dejeuner', 'jardin']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés', 'calme après 22h']),
                'note_moyenne' => 4.80,
                'nombre_avis' => 200,
            ],
            [
                'titre' => 'Hotel La Casa Cielo',
                'description' => 'Hôtel moderne et confortable à Cotonou, avec petit-déjeuner inclus. Chambres climatisées, connexion WiFi haut débit et parking sécurisé. Accueil chaleureux et service attentionné.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 20,
                'nombre_lits' => 20,
                'nombre_salles_bain' => 20,
                'capacite_max' => 40,
                'prix_par_nuit' => 55000,
                'adresse' => 'Quartier Agla, Rue Principale',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3512,
                'longitude' => 2.4098,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'parking', 'petit_dejeuner', 'cuisine']),
                'regles_maison' => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne' => 4.20,
                'nombre_avis' => 5,
            ],
            [
                'titre' => 'Résidences Hôtel Perle Bleue',
                'description' => 'Résidence hôtelière moderne proposant des appartements entièrement équipés. Idéale pour les longs séjours. Cuisine équipée, salon et terrasse privée disponibles dans chaque appartement.',
                'type' => 'appartement',
                'categorie' => 'confort',
                'nombre_pieces' => 3,
                'nombre_lits' => 2,
                'nombre_salles_bain' => 1,
                'capacite_max' => 4,
                'prix_par_nuit' => 60000,
                'adresse' => 'Quartier Fidjrossè, Cotonou',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3441,
                'longitude' => 2.3964,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'cuisine', 'parking', 'terrasse']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 5.00,
                'nombre_avis' => 2,
            ],
            [
                'titre' => 'Residence MaryHouse',
                'description' => 'Résidence accueillante avec vue sur la ville. Petit-déjeuner inclus et ambiance familiale. Idéale pour les petits budgets souhaitant un cadre propre et confortable à Cotonou.',
                'type' => 'appartement',
                'categorie' => 'budget',
                'nombre_pieces' => 2,
                'nombre_lits' => 2,
                'nombre_salles_bain' => 1,
                'capacite_max' => 4,
                'prix_par_nuit' => 35000,
                'adresse' => 'Quartier Cadjehoun, Cotonou',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3579,
                'longitude' => 2.3812,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'petit_dejeuner', 'cuisine']),
                'regles_maison' => json_encode(['non-fumeur']),
                'note_moyenne' => 4.70,
                'nombre_avis' => 118,
            ],
            [
                'titre' => 'Hotel Casa Cornelia',
                'description' => 'Petit hôtel de charme à Cotonou dans un cadre agréable et verdoyant. Service personnalisé et atmosphère conviviale. Situé dans un quartier calme, idéal pour un séjour reposant.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 10,
                'nombre_lits' => 10,
                'nombre_salles_bain' => 10,
                'capacite_max' => 20,
                'prix_par_nuit' => 65000,
                'adresse' => 'Quartier Mènontin, Cotonou',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3739,
                'longitude' => 2.4044,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'parking', 'jardin']),
                'regles_maison' => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne' => 4.30,
                'nombre_avis' => 3,
            ],
            [
                'titre' => 'Sofitel Cotonou Marina Hotel & Spa',
                'description' => 'Palace 5 étoiles de prestige situé en bord de mer à Cotonou. Spa de luxe, restaurant gastronomique, piscine à débordement, marina privée et salles de conférence ultramodernes. L\'adresse incontournable pour une expérience haut de gamme au Bénin.',
                'type' => 'hotel',
                'categorie' => 'luxe',
                'nombre_pieces' => 200,
                'nombre_lits' => 200,
                'nombre_salles_bain' => 200,
                'capacite_max' => 400,
                'prix_par_nuit' => 350000,
                'adresse' => 'Boulevard de la Marina',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3562,
                'longitude' => 2.4389,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'gym', 'spa', 'salle_conference', 'vue_mer', 'petit_dejeuner', 'marina']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés', 'check-in à 15h', 'check-out à 12h']),
                'note_moyenne' => 4.70,
                'nombre_avis' => 29,
            ],
            [
                'titre' => 'Gîte Chez Noël',
                'description' => 'Gîte authentique et chaleureux à Natitingou, porte d\'entrée du parc Pendjari. Idéal pour les amoureux de la nature et des traditions Atacora. Cuisine locale préparée à la demande.',
                'type' => 'maison',
                'categorie' => 'budget',
                'nombre_pieces' => 5,
                'nombre_lits' => 6,
                'nombre_salles_bain' => 2,
                'capacite_max' => 10,
                'prix_par_nuit' => 25000,
                'adresse' => 'Quartier Centre, Natitingou',
                'ville' => 'Natitingou',
                'code_postal' => '10',
                'latitude' => 10.3044,
                'longitude' => 1.3800,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'cuisine', 'jardin', 'parking']),
                'regles_maison' => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne' => 5.00,
                'nombre_avis' => 13,
            ],
            [
                'titre' => 'Benin Berge Hotel',
                'description' => 'Hôtel moderne et bien situé à Cotonou. Chambres confortables et bien décorées, service professionnel et rapport qualité-prix excellent. Proche des ambassades et des centres d\'affaires.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 35,
                'nombre_lits' => 35,
                'nombre_salles_bain' => 35,
                'capacite_max' => 70,
                'prix_par_nuit' => 70000,
                'adresse' => 'Quartier Haie Vive, Avenue Steinmetz',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3601,
                'longitude' => 2.4322,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'bar']),
                'regles_maison' => json_encode(['non-fumeur']),
                'note_moyenne' => 4.90,
                'nombre_avis' => 8,
            ],
            [
                'titre' => 'Résidences Ouadada',
                'description' => 'Résidence hôtelière de standing à Porto-Novo, la capitale du Bénin. Appartements meublés avec terrasse, accès au jardin et parking sécurisé. Idéale pour les séjours longue durée.',
                'type' => 'appartement',
                'categorie' => 'confort',
                'nombre_pieces' => 3,
                'nombre_lits' => 2,
                'nombre_salles_bain' => 1,
                'capacite_max' => 4,
                'prix_par_nuit' => 55000,
                'adresse' => 'Quartier Ouando, Porto-Novo',
                'ville' => 'Porto-Novo',
                'code_postal' => '02',
                'latitude' => 6.4913,
                'longitude' => 2.6244,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'cuisine', 'parking', 'jardin', 'terrasse']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 4.80,
                'nombre_avis' => 24,
            ],
            [
                'titre' => 'Hôtel Iya-Oasis',
                'description' => 'Hôtel accueillant à Parakou, la capitale économique du Nord-Bénin. Petit-déjeuner inclus, chambres spacieuses et climatisées. Parfait pour explorer le nord du pays.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 30,
                'nombre_lits' => 30,
                'nombre_salles_bain' => 30,
                'capacite_max' => 60,
                'prix_par_nuit' => 45000,
                'adresse' => 'Avenue de France, Parakou',
                'ville' => 'Parakou',
                'code_postal' => '07',
                'latitude' => 9.3569,
                'longitude' => 2.6287,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'petit_dejeuner']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 5.00,
                'nombre_avis' => 5,
            ],
            [
                'titre' => 'Benin Royal Hotel',
                'description' => 'Grand hôtel 4 étoiles de Cotonou avec piscine, restaurants, bar et centre de conférences. Chambres luxueuses avec vue sur la ville. Petit-déjeuner buffet inclus. Service de conciergerie disponible 24h/24.',
                'type' => 'hotel',
                'categorie' => 'luxe',
                'nombre_pieces' => 90,
                'nombre_lits' => 90,
                'nombre_salles_bain' => 90,
                'capacite_max' => 180,
                'prix_par_nuit' => 120000,
                'adresse' => 'Avenue Clozel, Quartier Ganhi',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3664,
                'longitude' => 2.4162,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'parking', 'gym', 'salle_conference', 'petit_dejeuner']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 4.20,
                'nombre_avis' => 116,
            ],
            [
                'titre' => 'Hôtel Les Orchidées',
                'description' => 'Hôtel élégant avec vue sur la ville de Cotonou. Petit-déjeuner inclus, restaurant sur place, piscine et personnel attentionné. Situation idéale pour explorer la capitale économique du Bénin.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 45,
                'nombre_lits' => 45,
                'nombre_salles_bain' => 45,
                'capacite_max' => 90,
                'prix_par_nuit' => 90000,
                'adresse' => 'Rue du Lycée Toffa, Cotonou',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3715,
                'longitude' => 2.4211,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'parking', 'petit_dejeuner', 'vue_ville']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 4.60,
                'nombre_avis' => 47,
            ],
            [
                'titre' => 'Le Bélier',
                'description' => 'Hôtel confortable à Natitingou, idéalement situé pour visiter le parc Pendjari et les châteaux Tata Somba. Cuisine locale et internationale, jardin verdoyant et atmosphère détendue.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 25,
                'nombre_lits' => 25,
                'nombre_salles_bain' => 25,
                'capacite_max' => 50,
                'prix_par_nuit' => 60000,
                'adresse' => 'Rue Principale, Natitingou Centre',
                'ville' => 'Natitingou',
                'code_postal' => '10',
                'latitude' => 10.3102,
                'longitude' => 1.3812,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'jardin']),
                'regles_maison' => json_encode(['non-fumeur']),
                'note_moyenne' => 4.80,
                'nombre_avis' => 18,
            ],
            [
                'titre' => 'Le Kare Ebene',
                'description' => 'Hôtel design et contemporain à Cotonou avec vue sur la ville. Petit-déjeuner inclus, décoration africaine moderne et service de qualité. À proximité des principales attractions de la ville.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 30,
                'nombre_lits' => 30,
                'nombre_salles_bain' => 30,
                'capacite_max' => 60,
                'prix_par_nuit' => 80000,
                'adresse' => 'Quartier Jéricho, Cotonou',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3782,
                'longitude' => 2.4088,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'petit_dejeuner', 'vue_ville']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 4.50,
                'nombre_avis' => 10,
            ],
            [
                'titre' => 'Hotel Awalé Plage',
                'description' => 'Hôtel en bord de mer à Grand Popo, village côtier pittoresque du Bénin. Accès direct à la plage, atmosphère décontractée et cadre naturel exceptionnel. Idéal pour les vacances balnéaires.',
                'type' => 'hotel',
                'categorie' => 'budget',
                'nombre_pieces' => 20,
                'nombre_lits' => 20,
                'nombre_salles_bain' => 20,
                'capacite_max' => 40,
                'prix_par_nuit' => 30000,
                'adresse' => 'Bord de Mer, Grand Popo',
                'ville' => 'Grand Popo',
                'code_postal' => '06',
                'latitude' => 6.2817,
                'longitude' => 1.8269,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'restaurant', 'plage', 'parking']),
                'regles_maison' => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne' => 3.60,
                'nombre_avis' => 136,
            ],
            [
                'titre' => 'La Maison de Canelya',
                'description' => 'Maison d\'hôtes chaleureuse et bien décorée à Cotonou. Ambiance familiale, jardin fleuri et service personnalisé. À quelques minutes des ambassades et des quartiers d\'affaires.',
                'type' => 'maison',
                'categorie' => 'confort',
                'nombre_pieces' => 6,
                'nombre_lits' => 8,
                'nombre_salles_bain' => 3,
                'capacite_max' => 12,
                'prix_par_nuit' => 65000,
                'adresse' => 'Quartier Agla, Cotonou',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3512,
                'longitude' => 2.4101,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'jardin', 'parking', 'cuisine']),
                'regles_maison' => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne' => 4.60,
                'nombre_avis' => 47,
            ],
            [
                'titre' => 'Chez Sabine',
                'description' => 'Auberge authentique à Abomey, la ville royale du Bénin. Petit-déjeuner local inclus, guide touristique disponible pour visiter les palais royaux. Une expérience culturelle unique.',
                'type' => 'maison',
                'categorie' => 'budget',
                'nombre_pieces' => 4,
                'nombre_lits' => 5,
                'nombre_salles_bain' => 2,
                'capacite_max' => 8,
                'prix_par_nuit' => 25000,
                'adresse' => 'Quartier Djègan-Kpèvi, Abomey',
                'ville' => 'Abomey',
                'code_postal' => '04',
                'latitude' => 7.1965,
                'longitude' => 1.9934,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'cuisine', 'jardin', 'petit_dejeuner']),
                'regles_maison' => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne' => 4.70,
                'nombre_avis' => 29,
            ],
            [
                'titre' => 'Djegba Hotel',
                'description' => 'Hôtel fonctionnel à Ouidah avec vue sur l\'océan. Petit-déjeuner servi sur place, chambres climatisées. Idéal pour découvrir la ville historique de Ouidah et la Route de l\'Esclave.',
                'type' => 'hotel',
                'categorie' => 'budget',
                'nombre_pieces' => 15,
                'nombre_lits' => 15,
                'nombre_salles_bain' => 15,
                'capacite_max' => 30,
                'prix_par_nuit' => 35000,
                'adresse' => 'Rue de l\'Atlantique, Ouidah',
                'ville' => 'Ouidah',
                'code_postal' => '03',
                'latitude' => 6.6214,
                'longitude' => 2.0855,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'vue_ocean']),
                'regles_maison' => json_encode(['non-fumeur']),
                'note_moyenne' => 3.70,
                'nombre_avis' => 26,
            ],
            [
                'titre' => 'Chez Monique',
                'description' => 'Auberge simple et économique à Abomey pour les voyageurs à petit budget. Proche du palais royal d\'Abomey classé au patrimoine mondial de l\'UNESCO. Cuisine béninoise traditionnelle disponible.',
                'type' => 'maison',
                'categorie' => 'budget',
                'nombre_pieces' => 3,
                'nombre_lits' => 4,
                'nombre_salles_bain' => 1,
                'capacite_max' => 6,
                'prix_par_nuit' => 20000,
                'adresse' => 'Route Abomey-Bohicon, Abomey',
                'ville' => 'Abomey',
                'code_postal' => '04',
                'latitude' => 7.2012,
                'longitude' => 1.9891,
                'statut' => 'actif',
                'amenagements' => json_encode(['cuisine', 'jardin']),
                'regles_maison' => json_encode(['non-fumeur', 'pas de bruit après 21h']),
                'note_moyenne' => 3.30,
                'nombre_avis' => 42,
            ],
            [
                'titre' => 'RESIDENCE MH SERVICES Cotonou',
                'description' => 'Résidence hôtelière moderne à Cotonou proposant des appartements entièrement équipés pour les courts et longs séjours. Idéale pour les expatriés et les voyageurs d\'affaires recherchant l\'indépendance.',
                'type' => 'appartement',
                'categorie' => 'confort',
                'nombre_pieces' => 3,
                'nombre_lits' => 2,
                'nombre_salles_bain' => 1,
                'capacite_max' => 4,
                'prix_par_nuit' => 60000,
                'adresse' => 'Quartier Haie Vive, Cotonou',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3604,
                'longitude' => 2.4341,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'cuisine', 'parking', 'sécurité_24h']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 5.00,
                'nombre_avis' => 1,
            ],
            [
                'titre' => 'Hotel La Mariella',
                'description' => 'Petit hôtel de charme à Ouidah dans un cadre verdoyant. Chambres confortables, service chaleureux et petit-déjeuner maison. À quelques minutes des sites historiques de Ouidah.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 12,
                'nombre_lits' => 14,
                'nombre_salles_bain' => 12,
                'capacite_max' => 24,
                'prix_par_nuit' => 70000,
                'adresse' => 'Route de la Forêt Sacrée, Ouidah',
                'ville' => 'Ouidah',
                'code_postal' => '03',
                'latitude' => 6.6198,
                'longitude' => 2.0841,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'jardin', 'parking', 'petit_dejeuner']),
                'regles_maison' => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne' => 5.00,
                'nombre_avis' => 1,
            ],
            [
                'titre' => 'Asva Beach Resort',
                'description' => 'Resort balnéaire de luxe à Grand Popo, directement sur l\'Atlantique. Villas privées avec accès direct à la plage, piscine à débordement, restaurant de fruits de mer et spa. Un paradis tropical sur la côte béninoise.',
                'type' => 'resort',
                'categorie' => 'luxe',
                'nombre_pieces' => 20,
                'nombre_lits' => 20,
                'nombre_salles_bain' => 20,
                'capacite_max' => 40,
                'prix_par_nuit' => 150000,
                'adresse' => 'Bord de l\'Atlantique, Grand Popo',
                'ville' => 'Grand Popo',
                'code_postal' => '06',
                'latitude' => 6.2789,
                'longitude' => 1.8244,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'piscine', 'restaurant', 'bar', 'spa', 'plage', 'parking']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés', 'check-in à 15h']),
                'note_moyenne' => 5.00,
                'nombre_avis' => 1,
            ],
            [
                'titre' => 'Residence Ivoire Cotonou',
                'description' => 'Résidence hôtelière élégante à Cotonou offrant des appartements meublés avec goût. Idéale pour les expatriés, les diplomates et les voyageurs d\'affaires en séjour prolongé.',
                'type' => 'appartement',
                'categorie' => 'confort',
                'nombre_pieces' => 4,
                'nombre_lits' => 3,
                'nombre_salles_bain' => 2,
                'capacite_max' => 6,
                'prix_par_nuit' => 65000,
                'adresse' => 'Quartier Cocotiers, Cotonou',
                'ville' => 'Cotonou',
                'code_postal' => '01',
                'latitude' => 6.3521,
                'longitude' => 2.4278,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'cuisine', 'parking', 'terrasse', 'sécurité_24h']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés']),
                'note_moyenne' => 5.00,
                'nombre_avis' => 2,
            ],
            [
                'titre' => 'Domaine de la Palmeraie',
                'description' => 'Domaine d\'exception à Ouidah, niché au cœur d\'une palmeraie centenaire. Villas privées avec piscine, service de chef personnel et activités culturelles. Une expérience de luxe unique dans un cadre naturel et historique.',
                'type' => 'villa',
                'categorie' => 'luxe',
                'nombre_pieces' => 6,
                'nombre_lits' => 8,
                'nombre_salles_bain' => 4,
                'capacite_max' => 12,
                'prix_par_nuit' => 200000,
                'adresse' => 'Route de Ouidah-Lomé, Ouidah',
                'ville' => 'Ouidah',
                'code_postal' => '03',
                'latitude' => 6.3611,
                'longitude' => 2.0888,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'piscine', 'cuisine', 'jardin', 'parking', 'chef_personnel', 'spa']),
                'regles_maison' => json_encode(['non-fumeur', 'animaux non autorisés', 'check-in sur rendez-vous']),
                'note_moyenne' => 5.00,
                'nombre_avis' => 3,
            ],
            [
                'titre' => 'Auberge Kalaupapa',
                'description' => 'Auberge de charme à Abomey-Calavi, à proximité immédiate de Cotonou et du lac Nokoué. Ambiance conviviale, chambres propres et confortables. Idéale pour découvrir Ganvié, le village sur pilotis.',
                'type' => 'hotel',
                'categorie' => 'confort',
                'nombre_pieces' => 15,
                'nombre_lits' => 18,
                'nombre_salles_bain' => 15,
                'capacite_max' => 30,
                'prix_par_nuit' => 55000,
                'adresse' => 'Quartier Godomey, Abomey-Calavi',
                'ville' => 'Abomey-Calavi',
                'code_postal' => '01',
                'latitude' => 6.4487,
                'longitude' => 2.3559,
                'statut' => 'actif',
                'amenagements' => json_encode(['wifi', 'climatisation', 'restaurant', 'parking', 'jardin']),
                'regles_maison' => json_encode(['non-fumeur', 'pas de bruit après 22h']),
                'note_moyenne' => 4.90,
                'nombre_avis' => 13,
            ],
        ];

        foreach ($hebergements as $data) {
            $data['user_id'] = $host->id;
            $data['date_verification'] = now();
            $data['nombre_reservations'] = 0;
            Hebergement::create($data);
        }
    }
}
